import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://parabank.parasoft.com/parabank/register.htm');
  await page.locator('[id="customer.firstName"]').click();
  await page.locator('[id="customer.firstName"]').press('CapsLock');
  await page.locator('[id="customer.firstName"]').fill('A');
  await page.locator('[id="customer.firstName"]').press('CapsLock');
  await page.locator('[id="customer.firstName"]').fill('Amit ');
  await page.locator('[id="customer.lastName"]').click();
  await page.locator('[id="customer.lastName"]').fill('pant');
  await page.locator('[id="customer.address.street"]').click();
  await page.locator('[id="customer.address.street"]').fill('s3kksis');
  await page.locator('[id="customer.address.city"]').click();
  await page.locator('[id="customer.address.city"]').fill('uttarpardesh');
  await page.locator('[id="customer.address.state"]').click();
  await page.locator('[id="customer.address.state"]').fill('UT');
  await page.locator('[id="customer.address.zipCode"]').click();
  await page.locator('[id="customer.address.zipCode"]').fill('1109092');
  await page.locator('[id="customer.phoneNumber"]').click();
  await page.locator('[id="customer.phoneNumber"]').fill('9289499648');
  await page.locator('[id="customer.ssn"]').click();
  await page.locator('[id="customer.ssn"]').fill('656sd65');
  await page.locator('[id="customer.username"]').click();
  await page.locator('[id="customer.username"]').fill('kira@91939');
  await page.locator('[id="customer.password"]').click();
  await page.locator('[id="customer.password"]').fill('Kira@91939');
  await page.locator('#repeatedPassword').click();
  await page.locator('#repeatedPassword').fill('Kira@91939');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByText('Your account was created').click();
  await page.getByText('Your account was created').dblclick();
  await page.getByRole('heading', { name: 'Welcome kira@' }).click();
  await page.getByRole('link', { name: 'Log Out' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Username' }).click();
  await page.locator('input[name="username"]').click();
  await page.locator('input[name="username"]').fill('kira@91939');
  await page.locator('input[name="username"]').press('Tab');
  await page.locator('input[name="password"]').press('CapsLock');
  await page.locator('input[name="password"]').fill('K');
  await page.locator('input[name="password"]').press('CapsLock');
  await page.locator('input[name="password"]').fill('Kira@91939');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByText('The username and password').click();
  await page.getByText('The username and password').click();
  await page.getByRole('heading', { name: 'Error!' }).click();
  await page.locator('input[name="username"]').click();
  await page.locator('input[name="username"]').fill('kira@91939');
  await page.locator('input[name="username"]').press('Tab');
  await page.locator('input[name="password"]').press('CapsLock');
  await page.locator('input[name="password"]').fill('K');
  await page.locator('input[name="password"]').press('CapsLock');
  await page.locator('input[name="password"]').fill('Kira@91939');
  await page.locator('input[name="password"]').press('Enter');
});